// examples/react/src/pages/sel-city/index.tsx
import { Button, View } from '@tarojs/components'
import React, { FC } from 'react'
import { Router } from 'tarojs-router-next'
import './index.css'

const Index: FC = () => {
  const cityList = [
    {
      id: 1,
      name: '深圳',
    },
    {
      id: 2,
      name: '广州',
    },
  ]

  const onSel = (index: number) => {
    Router.back(cityList[index])
  }

  return (
    <View>
      <View>
        {cityList.map((it, index) => {
          return (
            <View onClick={() => onSel(index)} className="item" key={it.id}>
              {it.name}
            </View>
          )
        })}
      </View>

      <Button
        onClick={() => {
          Router.back(Error('用户取消选择'))
        }}
      >
        取消选择
      </Button>
    </View>
  )
}

export default Index

// examples/vue3/src/pages/sel-city/index.vue
<template>
  <view class="index">
    <view class="item" v-for="(it, index) in cityList" :key="it.id" @tap="onSel(index)">{{ it.name }}</view>
    <button @tap="onCancel">取消选择</button>
  </view>
</template>

<script lang="ts">
import { ref } from 'vue'
import { Router } from 'tarojs-router-next'
import './index.scss'

export default {
  setup() {
    const cityList = ref([
      {
        id: 1,
        name: '深圳',
      },
      {
        id: 2,
        name: '广州',
      },
    ])

    const onSel = (index: number) => {
      Router.back(cityList.value[index])
    }

    const onCancel = () => {
      Router.back(new Error('用户取消选择'))
    }

    return {
      cityList,
      onSel,
      onCancel,
    }
  },
}
</script>
