// examples/vue3/src/pages/me/index.vue
<template>
  <view class="index">
    <text>该页面必须要登录，进得来说明已经登陆了</text>
    <view>我的信息 {{ JSON.stringify(userinfo) }}</view>
  </view>
</template>

<script>
import { UserStore } from '../../store/user'
import { ref } from 'vue'
import './index.scss'

export default {
  setup() {
    return {
      userinfo: UserStore.userinfo,
    }
  },
}
</script>

// examples/react/src/pages/me/index.tsx
import React, { FC } from 'react'
import { View } from '@tarojs/components'
import './index.css'
import { UserStore } from '../../store/user'

const Index: FC = () => {
  return (
    <View className="index">
      <View>该页面必须要登录，进得来说明已经登陆了</View>
      <View>我的信息：{JSON.stringify(UserStore.userinfo)}</View>
    </View>
  )
}

export default Index
