// examples/vue3/src/pages/page-data-params/index.vue
<template>
  <view class="index">
    <view>上一个页面带来的参数(请忽略 route_key )：</view>
    <view>{{ JSON.stringify(params) }}</view>

    <view>上一个页面带来的数据：</view>
    <view>{{ JSON.stringify(data) }}</view>
  </view>
</template>

<script lang="ts">
import { Router } from 'tarojs-router-next'
import './index.scss'

export default {
  setup() {
    const params = Router.getParams()
    const data = Router.getData()

    return {
      params,
      data,
    }
  },
}
</script>

// example/src/pages/page-data-params/index.tsx
import React, { FC } from 'react'
import { View, Text, Button } from '@tarojs/components'
import { useRouter } from 'tarojs-router'
import './index.css'

const Index: FC = () => {
  const { params, data } = useRouter()
  return (
    <View className='index'>
      <View>上一个页面带来的参数：</View>
      <View>{JSON.stringify(params)}</View>

      <View>上一个页面带来的数据：</View>
      <View>{JSON.stringify(data)}</View>
    </View>
  )
}

export default Index
